import type { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import Tile from '../components/Tile';
import Diem from '../components/Diem';
import Nav from '../components/Nav';
import styles from '../styles/Home.module.css';

const Diems: NextPage = () => {
  const [mainDiem, setDiem] = useState('');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={styles.container}>
        <div className={styles.tiles}>
          <Tile setDiem={setDiem} />
          <Tile setDiem={setDiem} />
          <Tile setDiem={setDiem} />
          <Tile setDiem={setDiem} />
        </div>
        <div className={styles.diem}>
          <Diem />
        </div>
      </main>
    </div>
  );
};

export default Diems;
