import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LoginForm from "../components/LoginForm";
import testHook from "../services/testHook";
import ChatServer from "../components/ChatServer";

const Home: NextPage = () => {
  const { state } = testHook();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
      <main className={styles.main}>
        {/* <LoginForm /> */}
        <ChatServer />
      </main>
    </div>
  );
};

export default Home;
