<<<<<<< HEAD
import React from "react";
=======
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import LoginForm from '../components/LoginForm';
>>>>>>> 7e9ffcb0f1dce6212910b98de6aed5f434e92502

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
      <main className={styles.main}>
        <LoginForm />
      </main>
    </div>
  );
};

<<<<<<< HEAD
export default index;
=======
export default Home;
>>>>>>> 7e9ffcb0f1dce6212910b98de6aed5f434e92502
