import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import testHook from '../services/testHook';
import ChatServer from '../components/ChatServer';

const Home: NextPage = () => {
  const { state } = testHook();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ChatServer />
      </main>
    </div>
  );
};

export default Home;
